In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr, '\n')
print(np.sqrt(arr), '\n')
print(np.exp(arr), '\n')
print(np.max(arr))
print(np.min(arr))
arr5 = np.array( [ 2.34, 3.879, -2.34, 0.434, -0.988, 234.234, 123123.113 ] )
print(arr5,'\n')
print(np.sqrt(arr5),'\n') # quando tem valor negativo retorna 'nan'
print(np.abs(arr5),'\n')
print(np.sign(arr5),'\n') # sinal de cada elemento
print(np.ceil(arr5),'\n')
print(np.floor(arr5),'\n')
print(np.rint(arr5),'\n') # arredonda para o inteiro mais próximo -- presenva o tipo de dado

print('\n\nVerificar nan','\n')
print(np.isnan(arr5),'\n') #retorna se o valor é 'nan'
arr6 = np.sqrt(arr5)
print(arr6)
print(np.isnan(arr6),'\n')
print(arr6[~np.isnan(arr6)],'\n') #filtrando valores que não são 'nan'

print('\n\nFunção para not logico','\n')
mask = np.isnan(arr6)
print(mask)
print(np.logical_not(mask))
print(~mask,'\n') # equivalente ao logical_not

[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

9
0
[ 2.34000000e+00  3.87900000e+00 -2.34000000e+00  4.34000000e-01
 -9.88000000e-01  2.34234000e+02  1.23123113e+05] 

[  1.52970585   1.96951771          nan   0.65878676          nan
  15.30470516 350.88903232] 

[2.34000000e+00 3.87900000e+00 2.34000000e+00 4.34000000e-01
 9.88000000e-01 2.34234000e+02 1.23123113e+05] 

[ 1.  1. -1.  1. -1.  1.  1.] 

[ 3.00000e+00  4.00000e+00 -2.00000e+00  1.00000e+00 -0.00000e+00
  2.35000e+02  1.23124e+05] 

[ 2.00000e+00  3.00000e+00 -3.00000e+00  0.00000e+00 -1.00000e+00
  2.34000e+02  1.23123e+05] 

[ 2.00000e+00  4.00000e+00 -2.00000e+00  0.00000e+00 -1.00000e+00
  2.34000e+02  1.23123e+05] 



Verificar nan 

[False False False False False False Fal

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in sqrt


In [3]:
#operações entre dois arrays
arr1 = (np.random.randn(5)*100).astype(np.int32)
arr2 = (np.random.randn(5)*100).astype(np.int32)
print(arr1,'\n')
print(arr2,'\n')
print(np.maximum(arr1,arr2),'\n')
print(np.minimum(arr1,arr2),'\n')

print(np.add(arr1, arr2), '\n')

arr3 = np.array( [ 2.34, 3.879, -2.34, 0.434, -0.988, 234.234, 123123.113 ] )
print(arr3,'\n')
frac, intei = np.modf(arr3)  #retorna a parte inteira e fracionaria de cada elemento do array
print(frac,'\n')
print(intei,'\n')

arr7 = np.arange(5)
print(arr7,'\n')
arr8 = np.array([2, 3, 2, 3, 2])
print(arr8,'\n')
print(np.power(arr7,arr8),'\n') #eleva os elementos do 1o array usando os elementos do 2o array como expoente



[  -4  119 -112   21  -79] 

[   0 -115  -88   43   19] 

[  0 119 -88  43  19] 

[  -4 -115 -112   21  -79] 

[  -4    4 -200   64  -60] 

[ 2.34000000e+00  3.87900000e+00 -2.34000000e+00  4.34000000e-01
 -9.88000000e-01  2.34234000e+02  1.23123113e+05] 

[ 0.34   0.879 -0.34   0.434 -0.988  0.234  0.113] 

[ 2.00000e+00  3.00000e+00 -2.00000e+00  0.00000e+00 -0.00000e+00
  2.34000e+02  1.23123e+05] 

[0 1 2 3 4] 

[2 3 2 3 2] 

[ 0  1  4 27 16] 



In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
xs, ys = np.meshgrid(x, y) #cria uma relação (x,y) -- todos de x com todos de y - matriz de coordenadas
print(xs)
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [5]:
#logica condicional - np.where(cond, valorVerdade, valorFalso)
media = np.array([1.5, 2.0, 7.5, 8.0, 10.0, 5.4, 5.4])
mask = media >= 5
print(media)
print(mask)
print(np.where(mask, 'aprovado', 'reprovado'))
print(np.where(media>=5, 'aprovado', 'reprovado')) #sem a variavel mask

print('\n\noutro exemplo - usando arrays\n')
dados = np.array([15,50,26,10,18,26,14,9])
print(dados)
mask = dados > 18
print(mask)
vVerdade = np.array([50,55,25,15,10,20,5,90])
vFalso = np.array([11,7,42,99,6,88,24,64])
print(vVerdade)
print(vFalso)
print(np.where(mask, vVerdade, vFalso))

print('\n\noutro exemplo - array bidimensional\n')
arr2d = (np.random.randn(4,4) * 1000).astype(np.int32)
print(arr2d,'\n')
print(np.where(arr2d<=0, 0, arr2d),'\n')  #os valores negativos são substituidos por zero e os positivos são mantidos
mask = (arr2d<=0) | (arr2d>=10)
print(np.where((arr2d<=0) | (arr2d>=500) , 0, arr2d),'\n')  #valores negativos ou maiores do que 500 são substituidos por zero e os positivos são mantidos

[ 1.5  2.   7.5  8.  10.   5.4  5.4]
[False False  True  True  True  True  True]
['reprovado' 'reprovado' 'aprovado' 'aprovado' 'aprovado' 'aprovado'
 'aprovado']
['reprovado' 'reprovado' 'aprovado' 'aprovado' 'aprovado' 'aprovado'
 'aprovado']


outro exemplo - usando arrays

[15 50 26 10 18 26 14  9]
[False  True  True False False  True False False]
[50 55 25 15 10 20  5 90]
[11  7 42 99  6 88 24 64]
[11 55 25 99  6 20 24 64]


outro exemplo - array bidimensional

[[ -496  -187  -339  -951]
 [ -498  -729   309  -606]
 [-1363  -806   498  -592]
 [ 1959  -731  1652   479]] 

[[   0    0    0    0]
 [   0    0  309    0]
 [   0    0  498    0]
 [1959    0 1652  479]] 

[[  0   0   0   0]
 [  0   0 309   0]
 [  0   0 498   0]
 [  0   0   0 479]] 



In [6]:
#estatistica
arr10 = np.abs((np.random.randn(5,4)*100).astype(np.int32))
print(arr10)
print(arr10.mean()) #calcula a media de todos os elementos
print(np.mean(arr10))
print(arr10.sum()) #soma
print(np.sum(arr10)) #soma
print(arr10.mean(axis=0)) #media ao longo das linhas -- media de cada coluna
print(arr10.mean(axis=1)) #media ao longo das colunas -- media de cada linha
print(arr10.sum(axis=0)) #soma ao longo das linhas -- soma de cada coluna
print(arr10.sum(axis=1)) #som ao longo das colunas -- som de cada linha

print('\n\nSoma Acumulada\n')
arr11 = np.abs((np.random.randn(10)*100).astype(np.int32))
print(arr11)
print(arr11.cumsum())
print(arr10.cumsum()) #soma cumulada
print(arr10.cumsum(axis=0)) #soma cumulada pelas linhas
print(arr10.cumsum(axis=1)) #soma cumulada pelas colunas

print('\n\nProduto Acumulado\n')
arr11 = np.abs((np.random.randn(10)*100).astype(np.int32))
print(arr11)
print(arr11.cumprod())

[[274  16  94  59]
 [ 21  10  34  83]
 [ 58 268  41  96]
 [189  45  51 125]
 [107 257  25  73]]
96.3
96.3
1926
1926
[129.8 119.2  49.   87.2]
[110.75  37.   115.75 102.5  115.5 ]
[649 596 245 436]
[443 148 463 410 462]


Soma Acumulada

[ 10 162 106 225 112  90 101  82  61  76]
[  10  172  278  503  615  705  806  888  949 1025]
[ 274  290  384  443  464  474  508  591  649  917  958 1054 1243 1288
 1339 1464 1571 1828 1853 1926]
[[274  16  94  59]
 [295  26 128 142]
 [353 294 169 238]
 [542 339 220 363]
 [649 596 245 436]]
[[274 290 384 443]
 [ 21  31  65 148]
 [ 58 326 367 463]
 [189 234 285 410]
 [107 364 389 462]]


Produto Acumulado

[115  32  88   5 182 169  24  69  88  51]
[        115        3680      323840     1619200   294694400 -1736253952
  1279578112 -1903423488     2457600   125337600]


In [7]:
#estatistica
arr12 = np.abs((np.random.randn(10)*100).astype(np.int32))
print(arr12)
print('Media: ',np.mean(arr12))
print('Desv Pad: ',np.std(arr12))
print('Variancia: ',np.var(arr12))

[ 11  50  30 110   7 174   6 240 156 140]
Media:  92.4
Desv Pad:  78.82918241362142
Variancia:  6214.040000000001


In [8]:
#aplicação em booleanos --- true = 1 e false = 0
arr13 = (np.random.randn(10)*100).astype(np.int32)
print(arr13)
print(arr13>0)
print((arr13>=0).sum())
print((arr13<0).sum())

result = np.array([False, True, False, True, True])
print(result)
print(result.any()) #verifica se há algum True
print(result.all()) #verifica se todos são True
result = np.array([False, False, False, False, False])
print(result)
print(result.any()) #verifica se há algum True
print(result.all()) #verifica se todos são True
result = np.array([True, True, True, True, True])
print(result)
print(result.any()) #verifica se há algum True
print(result.all()) #verifica se todos são True

[ 206   15 -290 -147  129  -90  -45   69   73   53]
[ True  True False False  True False False  True  True  True]
6
4
[False  True False  True  True]
True
False
[False False False False False]
False
False
[ True  True  True  True  True]
True
True


In [9]:
#ordenação
arr14 = (np.random.randn(10)*100).astype(np.int32)
print(arr14)
arr14.sort()
print(arr14)
print('\n\nArray 2D\n')
arr15 = np.abs((np.random.randn(4,3)*100).astype(np.int32))
print(arr15,'\n')
arr15.sort()
print(arr15,'\n')
arr15 = np.abs((np.random.randn(4,3)*100).astype(np.int32))
print(arr15,'\n')
print('\nOrdenação pelas linhas --- colunas ordenadas --- axis=0\n')
arr15.sort(axis=0)
print(arr15,'\n')
print('\nOrdenação pelas colunas --- linhas ordenadas --- axis=1\n')
arr15 = np.abs((np.random.randn(4,3)*100).astype(np.int32))
print(arr15,'\n')
arr15.sort(axis=1)
print(arr15,'\n')

[120 -95 -78 -38 -66 -17  58 -59 -86 -28]
[-95 -86 -78 -66 -59 -38 -28 -17  58 120]


Array 2D

[[216  49  58]
 [ 59 172  34]
 [ 91 178 207]
 [ 54 142   1]] 

[[ 49  58 216]
 [ 34  59 172]
 [ 91 178 207]
 [  1  54 142]] 

[[147 128 149]
 [106 123   6]
 [ 41 130 103]
 [  8  27  25]] 


Ordenação pelas linhas --- colunas ordenadas --- axis=0

[[  8  27   6]
 [ 41 123  25]
 [106 128 103]
 [147 130 149]] 


Ordenação pelas colunas --- linhas ordenadas --- axis=1

[[164  45 104]
 [ 27  24  57]
 [ 19  69 197]
 [ 22 122  58]] 

[[ 45 104 164]
 [ 24  27  57]
 [ 19  69 197]
 [ 22  58 122]] 



In [10]:
#funções de conjuntos e unicidades
classes = np.array(['ABC', 'DEF', 'ABC', 'XYZ', 'IJK', 'ABC', 'XYZ', 'DEF', 'IJK','ABC', 'ABC'])
print(classes)
print(np.unique(classes))
print(set(classes)) #função python
print(sorted(set(classes)))  #função python

print('\n\nVerificar se elementos estão contidos em um vetor\n')
print(np.in1d(classes,['ABC','XYZ'])) #retorna um vetor com True e False

print('\n\nIntersecção\n')
print(np.intersect1d(classes,['XYZ', 'IJK'])) #retorna a insersecção ordenada

print('\n\nUnião\n')
print(np.union1d(classes,['XYZ', 'IJK'])) #retorna a uniao ordenada
print(np.union1d(['ABC', 'IJK'],['XYZ', 'IJK'])) #retorna a uniao ordenada

print('\n\nDiferença\n')
print(np.setdiff1d(classes,['XYZ', 'IJK'])) #retorna a diferença de A para B
print(np.setdiff1d(['ABC', 'IJK'],['XYZ', 'IJK'])) #retorna a diferença de A para B


print('\n\nDiferença Simetrica -- xor\n') #elementos que estão em apenas um dos conjuntos
print(np.setxor1d(classes,['XYZ', 'IJK'])) 
print(np.setxor1d(['ABC', 'IJK'],['XYZ', 'IJK']))




['ABC' 'DEF' 'ABC' 'XYZ' 'IJK' 'ABC' 'XYZ' 'DEF' 'IJK' 'ABC' 'ABC']
['ABC' 'DEF' 'IJK' 'XYZ']
{'IJK', 'ABC', 'XYZ', 'DEF'}
['ABC', 'DEF', 'IJK', 'XYZ']


Verificar se elementos estão contidos em um vetor

[ True False  True  True False  True  True False False  True  True]


Intersecção

['IJK' 'XYZ']


União

['ABC' 'DEF' 'IJK' 'XYZ']
['ABC' 'IJK' 'XYZ']


Diferença

['ABC' 'DEF']
['ABC']


Diferença Simetrica -- xor

['ABC' 'DEF']
['ABC' 'XYZ']
