In [1]:
import numpy as np

In [25]:
arr = np.array([[1, 2, 3], [4 ,5 ,6]])
print(arr)
arr2 = np.array([[10, 20, 30], [40 ,50 ,60]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [29]:
#operações aritméticas
print(arr - 1, '\n')
print(arr -  arr, '\n')
print(arr -  arr2, '\n')
print(arr2 -  arr, '\n')

print(arr * 2, '\n')
print(arr * arr, '\n')
print(arr * arr2, '\n')

print(arr ** 2, '\n')
print(arr ** 0.5, '\n')

#operações booleanas resultam em True ou False
print (arr > arr2, '\n')
print (arr2 > arr, '\n')
arr3 = np.array([[1, 20, 3], [140 , 25 ,60]])
print(arr2 > arr3, '\n')
print(arr3 > arr2, '\n')

print(arr3 > 18)

[[0 1 2]
 [3 4 5]] 

[[0 0 0]
 [0 0 0]] 

[[ -9 -18 -27]
 [-36 -45 -54]] 

[[ 9 18 27]
 [36 45 54]] 

[[ 2  4  6]
 [ 8 10 12]] 

[[ 1  4  9]
 [16 25 36]] 

[[ 10  40  90]
 [160 250 360]] 

[[ 1  4  9]
 [16 25 36]] 

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]] 

[[False False False]
 [False False False]] 

[[ True  True  True]
 [ True  True  True]] 

[[ True False  True]
 [False  True False]] 

[[False False False]
 [ True False False]] 

[[False  True False]
 [ True  True  True]]


In [43]:
#transposição
arr4 = np.arange(15).reshape((3,5))
print(arr4,'\n')
print(arr4.T,'\n')

print('\n\n Produto Interno \n\n')
arr5 = np.random.randn(6,3)
print(arr5,'\n')
print(arr5.T,'\n')

arr6 = np.dot(arr5, arr5.T)
print(arr6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



 Produto Interno 


[[ 0.26825098 -1.02858412 -0.084746  ]
 [-0.42553423 -0.40831214 -1.01078908]
 [-0.07920692 -2.61026289 -1.2307746 ]
 [-2.34222253 -0.93004973 -0.22889962]
 [-1.12212623 -1.11205021 -1.1219145 ]
 [ 0.59387157 -0.23955785  0.86428588]] 

[[ 0.26825098 -0.42553423 -0.07920692 -2.34222253 -1.12212623  0.59387157]
 [-1.02858412 -0.40831214 -2.61026289 -0.93004973 -1.11205021 -0.23955785]
 [-0.084746   -1.01078908 -1.2307746  -0.22889962 -1.1219145   0.86428588]] 

[[ 1.13712577  0.39149374  2.76793085  0.34772921  0.93790349  0.33246726]
 [ 0.39149374  1.36949274  2.34356081  1.60781569  2.06558565 -1.02850903]
 [ 2.76793085  2.34356081  8.33455223  2.89491836  4.37244744 -0.48547089]
 [ 0.34772921  1.60781569  2.89491836  6.4033939   3.91933713 -1.36601338]
 [ 0.93790349  2.06558565  4.37244744  3.91933713  3.75451509 -1.36965338]
 [ 0.33246726 -1.0