In [1]:
import numpy as np

In [3]:
#Dados aleatórios
data = np.random.rand(2,3) #linha, coluna
data

array([[0.96616688, 0.86137434, 0.15266367],
       [0.54113677, 0.84450414, 0.58860962]])

In [8]:
data = np.random.rand(23) # uma linha, X colunas
data

array([0.72991491, 0.20167184, 0.09177742, 0.81438281, 0.00967705,
       0.9685156 , 0.77745749, 0.39292868, 0.26805156, 0.35216387,
       0.17086987, 0.52047091, 0.29920981, 0.21343957, 0.09022963,
       0.32493667, 0.09264069, 0.52498538, 0.49010553, 0.79233356,
       0.09577239, 0.41337369, 0.46687066])

In [35]:
data = np.random.rand(2,3)
print(data)
#operações matemáticas
print(data + data) 

[[0.57599189 0.38804027 0.85919069]
 [0.74776177 0.92112759 0.59642709]]
[[1.15198377 0.77608054 1.71838138]
 [1.49552353 1.84225517 1.19285418]]


In [37]:
#tamanho e tipo de dado
print(data.shape) #dimensões
lin,col = data.shape
print('#linhas: ',lin," #colunas: ",col)
print(data.dtype)
print(type(data)) #numpy array

(2, 3)
#linhas:  2  #colunas:  3
float64
<class 'numpy.ndarray'>


In [59]:
#criando arrays
data2 = [1, 3, 4, 5.6, 3.6]
print(data2)
print(type(data2)) #list
arr1 = np.array(data2)
print(arr1)
print(type(arr1)) #numpy array --- os dados possuem o mesmo tipo
print(arr1.dtype)
print('exemplo com caractere/string')
data2 = [1, 3, 4, 5.6, 3.6, 'a']
print(data2)
print(type(data2)) #list
arr1 = np.array(data2)
print(arr1) #numpy array --- os dados possuem o mesmo tipo
print(arr1.dtype) #unicode 32

[1, 3, 4, 5.6, 3.6]
<class 'list'>
[1.  3.  4.  5.6 3.6]
<class 'numpy.ndarray'>
float64
exemplo com caractere/string
[1, 3, 4, 5.6, 3.6, 'a']
<class 'list'>
['1' '3' '4' '5.6' '3.6' 'a']
<U32


In [113]:
#criação com tipos definidos
print(np.array([1,2,3], dtype=np.float64))
print(np.array([1,2,3], dtype=np.float64).dtype)
print(np.array([1,2,3], dtype=np.int32))
print(np.array([1,2,3], dtype=np.int32).dtype)
print(np.array([1,2,3], dtype=np.unicode_))
print(np.array([1,2,3], dtype=np.unicode_).dtype)

#conversão de tipos - note que pode ser utilizado o dtype de outro array para fazer as conversões
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)
arr = arr.astype(np.unicode_) #convertendo de float para string
print(arr)
print(arr.dtype)

arr = arr.astype(np.float64) #convertendo de string (unicode) para float
print(arr)
print(arr.dtype)
arr = np.array([1.9,2.8,3.7,4.6,5.5,6.4,0.3])
print(arr)
print(arr.dtype)
arr = arr.astype(np.int32) #obtem somente a parte inteira
print(arr)
print(arr.dtype)   


[1. 2. 3.]
float64
[1 2 3]
int32
['1' '2' '3']
<U1
[1 2 3]
int32
[1. 2. 3.]
float64
['1.0' '2.0' '3.0']
<U32
[1. 2. 3.]
float64
[1.9 2.8 3.7 4.6 5.5 6.4 0.3]
float64
[1 2 3 4 5 6 0]
int32


In [54]:
data2 = [[1,2,3], [4,5,6]]
print(data2) #list
arr2 = np.array(data2)
print(arr2) #numpy array
print('#dimensoes: ',arr2.ndim)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
#dimensoes:  2


In [94]:
#inicializando arrays
z = np.zeros(10)
print(z)
print()
print(z+1)
print()
z2 = np.zeros((2,3)) #passa-se uma tupla
print(z2)
print()
print(z2+1)
print()
z3 = np.empty((5,5))  #array vazio sem inicalizar a área de memória
print(z3)
print()
z4 = np.arange(10) #variação do range
print(z4)
z4 = np.arange(5,10)
print(z4)
z5 = np.ones(10)
print(z5)
a = np.array(['1','2','4','asdf'])
z6 = np.ones_like(a) #cria um array com o mesma dimensão e formato do array passado pelo parametro -- tambem há o zeros_like
print(a)
print(z6)
#preencher com valor específico
print(np.full((2, 2), 10))
print(np.full((2, 2), '10'))
print(np.full_like(a, 15)) #também existe o full_like

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1.16403662e-311 7.26276499e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [1.16096346e-028 1.04857803e-142 1.16467185e-028 1.12576162e-153
  3.24249977e-086]
 [6.98684252e-077 7.18988932e+140 3.44357625e-086 4.57890143e-072
  1.12590729e-153]
 [3.44357625e-086 1.12579529e-153 4.10113497e+223 1.12576162e-153
  1.21691794e+132]
 [3.44357625e-086 1.12594083e-153 8.53715287e+136 4.05174047e-317
  0.00000000e+000]]

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
['1' '2' '4' 'asdf']
['1' '1' '1' '1']
[[10 10]
 [10 10]]
[['10' '10']
 ['10' '10']]
['15' '15' '15' '15']


In [84]:
#conversão
print(np.array((1,2,3,4,5))) #tupla
print(type(np.array((1,2,3,4,5)))) #tupla
print(np.array([1,2,3,4,5])) #lista
print(type(np.array([1,2,3,4,5]))) #lista

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [116]:
#arange
print(np.arange(5,10,1))
print(np.arange(5,10,0.5))
print(np.arange(5,10,0.01))

[5 6 7 8 9]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[5.   5.01 5.02 5.03 5.04 5.05 5.06 5.07 5.08 5.09 5.1  5.11 5.12 5.13
 5.14 5.15 5.16 5.17 5.18 5.19 5.2  5.21 5.22 5.23 5.24 5.25 5.26 5.27
 5.28 5.29 5.3  5.31 5.32 5.33 5.34 5.35 5.36 5.37 5.38 5.39 5.4  5.41
 5.42 5.43 5.44 5.45 5.46 5.47 5.48 5.49 5.5  5.51 5.52 5.53 5.54 5.55
 5.56 5.57 5.58 5.59 5.6  5.61 5.62 5.63 5.64 5.65 5.66 5.67 5.68 5.69
 5.7  5.71 5.72 5.73 5.74 5.75 5.76 5.77 5.78 5.79 5.8  5.81 5.82 5.83
 5.84 5.85 5.86 5.87 5.88 5.89 5.9  5.91 5.92 5.93 5.94 5.95 5.96 5.97
 5.98 5.99 6.   6.01 6.02 6.03 6.04 6.05 6.06 6.07 6.08 6.09 6.1  6.11
 6.12 6.13 6.14 6.15 6.16 6.17 6.18 6.19 6.2  6.21 6.22 6.23 6.24 6.25
 6.26 6.27 6.28 6.29 6.3  6.31 6.32 6.33 6.34 6.35 6.36 6.37 6.38 6.39
 6.4  6.41 6.42 6.43 6.44 6.45 6.46 6.47 6.48 6.49 6.5  6.51 6.52 6.53
 6.54 6.55 6.56 6.57 6.58 6.59 6.6  6.61 6.62 6.63 6.64 6.65 6.66 6.67
 6.68 6.69 6.7  6.71 6.72 6.73 6.74 6.75 6.76 6.77 6.78 6.79 6.8  6.81
 6.82 6.83 6.84 6.85 6.